-- MIXED Profiles for Horizontal Aluminum (Category ID: 3606)
-- RAIL + GAP + WIDTH + BODY combinations


-- RAIL = 3-rail
-- GAP = 1
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '37', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-37-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '37', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-37-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '40-1-2', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-40-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '40-1-2', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-40-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '44', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-44-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '44', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-44-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '47-1-2', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-47-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '47-1-2', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-47-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '51', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-51-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '51', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-51-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '54-1-2', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-54-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '54-1-2', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-54-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '58', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-58-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '58', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-58-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '61-1-2', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-61-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '61-1-2', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-61-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '65', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-65-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '65', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-65-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '68-1-2', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-68-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '68-1-2', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-68-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '72', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-72-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '72', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-72-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '75-1-2', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-75-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '75-1-2', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-75-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '79', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-79-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '79', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-79-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '82-1-2', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-82-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '82-1-2', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-82-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '86', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-86-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '86', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-86-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '89-1-2', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-89-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '89-1-2', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-89-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '93', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-93-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '93', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-93-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '96-1-2', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-96-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '96-1-2', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-96-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '100', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-100-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '100', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-100-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '103-1-2', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-103-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '103-1-2', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-103-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '107', '1', '3-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-107-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '107', '1', '3-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-3-RAIL-1-GAP-107-BODY-8-WIDE-2.pdf', NOW());

-- RAIL = 4-rail
-- GAP = 1
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '34-1-2', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-34-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '34-1-2', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-34-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '38', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-38-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '38', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-38-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '41-1-2', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-41-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '41-1-2', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-41-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '45', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-45-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '45', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-45-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '48-1-2', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-48-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '48-1-2', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-48-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '52', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-52-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '52', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-52-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '55-1-2', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-55-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '55-1-2', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-55-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '59', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-59-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '59', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-59-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '62-1-2', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-62-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '62-1-2', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-62-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '66', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-66-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '66', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-66-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '69-1-2', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-69-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '69-1-2', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-69-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '73', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-73-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '73', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-73-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '76-1-2', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-76-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '76-1-2', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-76-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '80', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-80-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '80', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-80-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '83-1-2', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-83-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '83-1-2', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-83-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '87', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-87-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '87', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-87-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '90-1-2', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-90-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '90-1-2', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-90-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '94', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-94-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '94', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-94-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '97-1-2', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-97-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '97-1-2', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-97-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '101', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-101-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '101', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-101-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '104-1-2', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-104-12-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '104-1-2', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-104-12-BODY-8-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '108', '1', '4-rail', '6', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-108-BODY-6-WIDE-2.pdf', NOW());
INSERT INTO wpg0_profiles (category_id, body_height, gap, rail_size, panel_width, pdf_url, created_at) VALUES (3606, '108', '1', '4-rail', '8', 'https://staging2.wholesalefencing.com/wp-content/uploads/profiles/MIXED-4-RAIL-1-GAP-108-BODY-8-WIDE-2.pdf', NOW());